name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Set up environment variables
        run: echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV

      - name: Run tests
        run: go test $(go list ./... | grep -v 'repositories')
        working-directory: ./task_manager_test/test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
            name: coverage-report
            path: coverage.out
