name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: set up environmental variables
        env:
          JWT_SECRET: $ {{secrets.JWT_SECRET}}

      - name: Run infrastructure tests
        run: go test ./infrastructure/... -V
        working-directory: ./task_manager_test/test

      - name: Run controllers tests
        run: go test ./controllers/... -v
        working-directory: ./task_manager_test/test

      - name: Run usecase tests
        run: go test ./usecases/... -v
        working-directory: ./task_manager_test/test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
            name: coverage-report
            path: coverage.out
